version: '3.5'
services:
  wordpress:
    image: wordpress:6.0.2
    restart: on-failure
    ports:
    - 80:80
    volumes:
      - type: bind
        source: ${HOST_PROJECT_PATH}/wp-content/themes/NeoBCB21
        target: /var/www/html/wp-content/themes/NeoBCB21
      # - type: bind
      #   source: ${HOST_PROJECT_PATH}/wp-content/plugins/MyPluginName
      #   target: /var/www/html/wp-content/plugins/MyPluginName
      - type: bind
        source: ${HOST_PROJECT_PATH}/wp-content/uploads
        target: /var/www/html/wp-content/uploads
      - type: bind
        source: ${HOST_PROJECT_PATH}/wp-config/wp-config.php
        target: /var/www/html/wp-config.php
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: on-failure
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bcbwp
    volumes:
      - type: bind
        source: ${HOST_PROJECT_PATH}/dbdata
        target: /var/lib/mysql
        bind:
          create_host_path: true
      - type: bind
        source: ${HOST_PROJECT_PATH}/migration-scripts
        target: /docker-entrypoint-initdb.d
  adminer:
    image: adminer:4.8.1
    restart: on-failure
    ports:
    - 8080:8080
    depends_on:
      - mysql